<a href="https://colab.research.google.com/github/mdmasoomcse/TNS-prcatice-sessions/blob/main/Mini_project_02_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
vechile={
    "Vechicle_ID":[1,2,3,4,5,6],
    "Manufacturer":["Honda","Swift","Maruthi","BMW","TATA","Siearra"],
    "Model":['XUV','XL20','DV22','WAG32','MGH1','MGH1'],
    "vehicle_type":["SUV","ELECTRIC","HATCHBACK","SEDAN","HATCHBACK","ELECTRIC"],
    "Battery_capacity":[250,652,668,120,340,329],
    "Range":[50,45,88,42,12,50],
    "Effiecency":[5,7,8,2,4,6],
    "charging_time":[5,7,6,4,5,7],
    "Top_speed":[200,250,150,220,115,120],
    "Motor_Power":[5,7,2,4,6,2],
    "price":[54,22,84,66,85,66],
    "Launch_Year":[2022,2025,2026,2022,2004,2025],
    "Safty_rating":[4,4,3,2,1,5]


}
df=pd.DataFrame(vechile)
df

,Vechicle_ID,Manufacturer,Model,vehicle_type,Battery_capacity,Range,Effiecency,charging_time,Top_speed,Motor_Power,price,Launch_Year,Safty_rating
0,1,Honda,XUV,SUV,250,50,5,5,200,5,54,2022,4
1,2,Swift,XL20,ELECTRIC,652,45,7,7,250,7,22,2025,4
2,3,Maruthi,DV22,HATCHBACK,668,88,8,6,150,2,84,2026,3
3,4,BMW,WAG32,SEDAN,120,42,2,4,220,4,66,2022,2
4,5,TATA,MGH1,HATCHBACK,340,12,4,5,115,6,85,2004,1
5,6,Siearra,MGH1,ELECTRIC,329,50,6,7,120,2,66,2025,5

In [19]:
df['Effiecency']=(df['Range']/df['Battery_capacity'])*100
df

,Vechicle_ID,Manufacturer,Model,vehicle_type,Battery_capacity,Range,Effiecency,charging_time,Top_speed,Motor_Power,price,Launch_Year,Safty_rating
0,1,Honda,XUV,SUV,250,50,20.000000,5,200,5,54,2022,4
1,2,Swift,XL20,ELECTRIC,652,45,6.901840,7,250,7,22,2025,4
2,3,Maruthi,DV22,HATCHBACK,668,88,13.173653,6,150,2,84,2026,3
3,4,BMW,WAG32,SEDAN,120,42,35.000000,4,220,4,66,2022,2
4,5,TATA,MGH1,HATCHBACK,340,12,3.529412,5,115,6,85,2004,1
5,6,Siearra,MGH1,ELECTRIC,329,50,15.197568,7,120,2,66,2025,5

In [21]:
#to classify vehicle on efficiency
def classify_efficiency(efficiency_value):
  if efficiency_value > 8:
    return "Excellent"
  elif efficiency_value >= 6 and efficiency_value < 8:
    return "Good"
  elif efficiency_value > 4 and efficiency_value <= 6:
    return "Average"
  else:
    return "Poor"

df['Efficiency_Class'] = df['Effiecency'].apply(classify_efficiency)
df

,Vechicle_ID,Manufacturer,Model,vehicle_type,Battery_capacity,Range,Effiecency,charging_time,Top_speed,Motor_Power,price,Launch_Year,Safty_rating,Efficiency_Class
0,1,Honda,XUV,SUV,250,50,20.000000,5,200,5,54,2022,4,Excellent
1,2,Swift,XL20,ELECTRIC,652,45,6.901840,7,250,7,22,2025,4,Good
2,3,Maruthi,DV22,HATCHBACK,668,88,13.173653,6,150,2,84,2026,3,Excellent
3,4,BMW,WAG32,SEDAN,120,42,35.000000,4,220,4,66,2022,2,Excellent
4,5,TATA,MGH1,HATCHBACK,340,12,3.529412,5,115,6,85,2004,1,Poor
5,6,Siearra,MGH1,ELECTRIC,329,50,15.197568,7,120,2,66,2025,5,Excellent

In [2]:
def effiecency():
  a = int(input("Enter efficiency"))
  if a > 8:
    print("Excellent")
  elif a >= 6 and a < 8: # Covers values 6 and 7
    print("Good")
  elif a > 4 and a <= 6: # Covers values 5 and 6
    print("Average")
  else: # Covers values 4 and below
    print("Poor")
effiecency()

Enter efficiency5
Average

In [7]:
def calu():
 a=int(input("Enter efficincy"))
 b=int(input("Enter range"))
 c=int(input("Battery Capacity"))
 d=b/c
 print(d)
calu()

Enter efficincy852
Enter range50
Battery Capacity55
0.9090909090909091